"use client";

import type { Business } from "@/lib/types";

export function RedesignModal({ business, onClose }: { business: Business; onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
      <div className="bg-[var(--card)] border border-[var(--border)] rounded-2xl max-w-2xl w-full max-h-[85vh] overflow-y-auto flex flex-col p-6 space-y-4 relative shadow-2xl">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-[var(--muted-foreground)] hover:text-[var(--foreground)] text-lg"
        >
          ✕
        </button>

        <div className="space-y-1">
          <span className="text-[10px] bg-[var(--primary)]/10 border border-[var(--primary)]/30 text-[var(--primary)] px-2 py-0.5 rounded-full uppercase tracking-wider">
            Stitch Redesign Preview
          </span>
          <h2 className="text-xl font-bold text-[var(--foreground)]">{business.name}</h2>
          <p className="text-xs text-[var(--muted-foreground)]">
            {business.category} • {business.address}
          </p>
        </div>

        <div className="border-t border-[var(--border)] pt-4 space-y-4">
          <div className="space-y-1">
            <h4 className="text-xs font-semibold text-[var(--foreground)] uppercase tracking-wider">AI Redesign Prompt</h4>
            <p className="text-xs text-[var(--muted-foreground)] bg-[var(--secondary)] border border-[var(--border)] p-3 rounded-lg leading-relaxed whitespace-pre-wrap">
              {business.redesign_prompt || "No prompt recorded."}
            </p>
          </div>

          {business.redesign_image_urls && business.redesign_image_urls.length > 0 ? (
            <div className="space-y-2">
              <h4 className="text-xs font-semibold text-[var(--foreground)] uppercase tracking-wider animate-pulse">
                Preview Screens
              </h4>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {business.redesign_image_urls.map((url, idx) => (
                  <div key={idx} className="border border-[var(--border)] rounded-xl overflow-hidden bg-[var(--secondary)] relative">
                    <span className="absolute top-2 left-2 bg-black/70 text-[9px] font-medium text-white px-2 py-0.5 rounded">
                      {business.redesign_image_urls!.length === 1 ? "Mobile Screen" : `Screen ${idx + 1}`}
                    </span>
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={url}
                      alt={`Redesign screen ${idx + 1}`}
                      className="w-full h-auto object-cover max-h-[300px]"
                    />
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <div className="py-8 text-center text-xs text-[var(--muted-foreground)]">
              🛠️ Design screens are being generated by the agent. Check back in a few seconds!
            </div>
          )}
        </div>

        <div className="pt-2 border-t border-[var(--border)] flex justify-between items-center text-xs">
          <span className="text-[var(--muted-foreground)]">
            Redesigned on: {business.redesigned_at ? new Date(business.redesigned_at).toLocaleString() : "N/A"}
          </span>
          {business.stitch_project_id && (
            <span className="text-[var(--muted-foreground)] font-mono text-[10px]">
              Project ID: {business.stitch_project_id}
            </span>
          )}
        </div>
      </div>
    </div>
  );
}
